version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    container_name: P0
    environment:
      POSTGRES_PASSWORD: cloud
      POSTGRES_USER: cloud
      POSTGRES_DB: P0
